### ISSUE TITLE
RailsBridge JavaScript Workshop for Women in Chattanooga, TN

### ISSUE THREAD

**Issue by courtney** [railsbridge/organizing#64] opened 2015-02-23 16:35 UTC
Carbon Five and Society of Work in Chattanooga, TN would like to offer a Javascript workshop to anyone in the Chattanooga, Nashville, Atlanta area. We have March 14th as the best date and are looking for volunteers to teach and help organize.

We have a large open space, some small meeting rooms for classes to break out into, and solid Wi-Fi. This is the first workshop that has been hosted at Society of Work but we have hosted many at our San Francisco offices. 

Current status:

- We have venue and sponsor for the workshop (SoW & C5). 
- Co-organizers: Alex Cruikshank, Chris Keathley, Gregory Ostermayr, Mary Helen Miller and Courtney Hemphill.
- Date: March 14, 2015.
- Posted the workshop to Bridge Troll
- Posted the workshop to Meetup for publicity

ToDos:
- Order breakfast
- Order lunch
- Find a good place for the afterparty :tada:

**Comment by courtney** [comment] 2015-02-23 22:10
@acruikshank @keathley Do you guys know how we should handle breakfast and lunch? 
@millermh do you know of a good place for us to do an afterparty? We usually comp the volunteers a drink but otherwise it just needs to be a bar where everyone can chill out afterwards.

**Comment by mhelenm** [comment] 2015-02-24 02:11
Re: afterparty -- I'm thinking Community Pie would be good because it's close enough to walk, big enough for all of us, and has good pizza if people want dinner. I will call and see if we can reserve part of their bar area because it will be crowded on a Saturday night.

**Comment by acruikshank** [comment] 2015-02-25 16:22
@keaythley and I think Maple Street Biscuit company would be great for breakfast. I can take care of that. Taziki's (healthy Mediterranean) or Tony's (Lasagna) have been pretty popular catering options for DevLunch.

**Comment by courtney** [comment] 2015-02-25 18:19
@acruikshank @keathley - sounds like a plan. I'll let you handle it. Can we schedule a time to go through the curriculum?

**Comment by lilliealbert** [comment] 2015-02-27 01:52
@courtney Just published the Bridge Troll event!

One piece of feedback on your Bridge Troll posting, based on what happened at the recent JavaScript workshop: no one actually just wanted to focus on HTML & CSS, so even the beginner class started with the To Do List using jQuery curriculum. So you might consider changing the descriptions if you want to do something similar. 

@raorao's [workshop retro notes will probably useful for y'all](https://groups.google.com/forum/#!topic/railsbridge-workshops/-x4X-L2Fzaw) :tada:

**Comment by raorao** [comment] 2015-02-27 02:34
@courtney are you all using the js to do list curriculum? If so, I'll be sure to push some planned fixes as soon as I can. I'd also be happy to chat about our experience with the curriculum.

and :+1: to @lilliealbert's suggestion about the beginner level. If you're interested in pairing on writing an all-js beginniner curriculum, I'd love to pitch in!

**Comment by courtney** [comment] 2015-02-27 06:25
@lilliealbert This is super helpful advice - thanks! We were planning on leveraging the existing JS curriculum and maybe putting a bit of a spin on it. @raorao If you have some planned fixes we would be very grateful to get those before the class. We can absolutely help out with a pair on the all-js beginner curriculum. @acruikshank and @keathley are currently leading the charge on curriculum.

**Comment by mhelenm** [comment] 2015-03-01 20:41
@courtney @acruikshank @keathley Let's do the after party at Chattanooga Brewing Company. I talked to Community Pie, and they're already quite busy that night. CBC said we should be fine. 
Address is:
1804 Chestnut St
Chattanooga, TN 37405

@courtney Do we need to know how many women will be in each of the three levels ahead of time? Or will they be able to choose a track once they arrive? Also, would you be able to change the workshop times to EST instead of PDT just to avoid confusion? Thanks!

**Comment by keathley** [comment] 2015-03-02 18:11
@mhelenm That sounds good to me :tada:

**Comment by courtney** [comment] 2015-03-02 19:49
@mhelenm I'll update the times right now. Thanks for sending out the tweet! Afterparty location sounds good, we just need somewhere with enough room :)

Also, we usually run through the levels/tracks the morning of when everyone is there. If it seems like more people are going for one class over another we can stack more teachers there.

**Comment by courtney** [comment] 2015-03-02 19:54
@lilliealbert I made some updates to the BridgeTroll event based on your feedback and Mary's. It looks like it hasn't yet been published to the Railsbridge site. Would you mind publishing soon? (https://www.bridgetroll.org/)

**Comment by lilliealbert** [comment] 2015-03-03 02:10
@courtney Done -- I totally thought I'd hit that button before! O_O

**Comment by acruikshank** [comment] 2015-03-10 15:26
Breakfast catering is ready. Waiting to hear back about lunch.

**Comment by courtney** [comment] 2015-03-10 16:46
Thanks Alex!

c

On Tue, Mar 10, 2015 at 8:26 AM, Alex Cruikshank <notifications@github.com>
wrote:

> Breakfast catering is ready. Waiting to hear back about lunch.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/64#issuecomment-78077424>
> .
>



-- 
Courtney Hemphill
Carbon Five

415-546-0500 x 20 | http://www.carbonfive.com
<https://twitter.com/chemphill>
<http://www.linkedin.com/in/courtneyhemphill>

**Comment by acruikshank** [comment] 2015-03-10 18:33
Lunch catering is set up now too.

**Comment by millermh** [comment] 2015-03-10 18:35
Bravo! Thanks, Alex.

**Comment by millermh** [comment] 2015-03-12 13:04
We now have 26 people signed up.

@acruikshank <https://github.com/acruikshank> I know I said to order food
for 20. And I still think that at least a handful of people won't show.

But, does anyone have any insight about what percent of sign-ups will
actually come? Should we increase our food order?

**Comment by acruikshank** [comment] 2015-03-12 13:20
26 is great news. I got food for 30. If all 26 show and we get 6 volunteers, we'll just be a little short (I'll run out and get food for some of us). The bigger issue is that it's only Courtney, Chris, Jordan, Andrew and me confirmed as volunteers. That's 1/5 if everyone shows. We'll try to get more today.

**Comment by acruikshank** [comment] 2015-03-12 13:31
Actually Chris got Winston and he might get Sean too, so I think we're ok with volunteers.

**Comment by lilliealbert** [comment] 2015-07-22 14:26
This happened!! Yay! https://www.bridgetroll.org/events/152

**Closed by lilliealbert** 2015-07-22 14:26 UTC
