### ISSUE TITLE
open source pairing workshop: 8/3 @Indiegogo

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/organizing#77] opened 2015-07-18 17:36 UTC
The [first open source pairing workshop](https://www.bridgetroll.org/events/174) went well -- shall we do it again?

background: an intermediate workshop where we would pair more experienced devs (anyone who knows JS and/or Ruby who has done a pull request before and is comfortable diving into a new open source project) with workshop grads.

Project: [open source project](https://github.com/18F/open-data-maker)  -- it is a good-for-the-world open data project that will feature an exciting new data set and could end up getting some news coverage in late summer (was originally going to include Bridge Troll too, but since Carbon Five is already focusing their July "junior jump" series on that, I want to try this out with an evening event focus on just one project)

- [x] location: Indiegogo (yay!)
- [X] organizers:  @aneyzberg, @ultrasaurus and @ange3 (Indiegogo liason) 
- [X] confirm date -- confirm @shawnbot can come, location & co-organizer
- [X] a few volunteers to seed the event with -- please chime in on this issue if you are interested in being the more experienced side of a pair (we'll have a range of issues to work on so you don't need to be super experienced)

**Comment by shamus** [comment] 2015-07-19 17:11
I'll definitely volunteer.

**Comment by siruguri** [comment] 2015-07-20 16:56
Will volunteer.

**Comment by aneyzberg** [comment] 2015-07-20 17:12
I can co-organize if you still need someone

**Comment by ange3** [comment] 2015-07-25 06:05
Hi volunteers! We've confirmed the next workshop for 8/3 (Mon) from 6-9 pm at Indiegogo, 965 Mission Street. Hope you can make it!

**Comment by ultrasaurus** [comment] 2015-07-25 11:21
@aneyzberg that would be awesome.  Could you make a bridgetroll event with the info from this story (above)?  Let's start with openings 6 students, since we know we have 4 volunteers, and it worked fine to have 2 students per volunteer last time, and then it'll be ok if students no-show.

Please include supervised kid time (we really need to do a pull request and not call it 'childcare') -- if anyone needs to bring along a kiddo, I'll find a babysitter and Bridge Foundry can spring for the cost if we don't get a sponsor.  Let's not commit to food yet.

Please add @ange3 and me as co-organizers.  Flying home today, not sure if I'll have wifi on the flight, but will check in tomorrow (Sunday).

Thanks everyone!

**Comment by aneyzberg** [comment] 2015-07-26 02:03
@ultrasaurus That sounds good. Posting shortly.

**Comment by aneyzberg** [comment] 2015-07-26 02:38
@ultrasaurus I am ready to post,  but wanted to clarify a couple things before I did. Are the following the same as what was the case at the C5 workshop  -
Time - 6-10pm?
Volunteer details - 
Be sure to set up your machine with the project: https://github.com/18F/open-data-maker (requires Ruby and Elastic Search).

Will wait for confirmation before I post the event.

**Comment by ultrasaurus** [comment] 2015-07-26 05:47
@ange3 said 6-9p at Indiegogo, I think it would be good if we could extend till 10p, but if we need to end at 9p, we can make that work.  We can always extend it if we hear :+1: from her.  Volunteer details are the same.

Thanks!

**Comment by ultrasaurus** [comment] 2015-07-26 06:13
@aneyzberg also, pls post the link here too so everyone who chimed in as a volunteer can sign up.  Thank you for taking the lead on this!

**Comment by ange3** [comment] 2015-07-26 08:35
Will check on Monday about 6-10 pm and let you know!

**Comment by aneyzberg** [comment] 2015-07-26 16:32
Here is the link: https://www.bridgetroll.org/events/181

**Comment by ange3** [comment] 2015-07-26 18:27
Awesome!!

**Comment by angiegogo** [comment] 2015-07-27 20:37
6-10 pm is confirmed! Will order food tomorrow (based on the dietary restrictions on the bridge troll event).

**Comment by aneyzberg** [comment] 2015-07-27 20:42
great- event has been updated. https://www.bridgetroll.org/events/181 

@ultrasaurus  should be open the event to 8 people since we have 4 volunteers?

**Comment by iisa** [comment] 2015-07-30 07:28
hi there, checking in with bridgetroll event stats - 10 volunteers, 6 confirmed students with 29 waitlisted.  Should we open up the waitlist before end of the week and ask everyone to confirm their rsvps?

**Comment by ange3** [comment] 2015-07-30 08:21
We now have 11 volunteers so I think we should definitely get at least 5 students off the waitlist! @ultrasaurus what do you think?

I've ordered food for 24 people. You can contact me at 650-868-6580. We'll be meeting on the 5th floor of the building in the Events Space :) --> Added a note about that on the Railsbridge event.

**Comment by ultrasaurus** [comment] 2015-07-30 22:30
@aneyzberg or @ange3 can you add my _other_ BridgeTroll account as a co-organizer -- I renamed it to "the Real Sarah Allen."  I forgot about this issue that my account has.

We have LOTS of volunteers.   With 11 volunteers, I think we should accept at least 16 students... maybe even 18.  Can someone change the RSVP limit?

Thanks!

**Comment by iisa** [comment] 2015-07-30 22:52
Hi Hi, I just updated the workshop student count to 16 and sent an email to all & waitlisted attendees to update their RSVP if needed.

I find that checking in a few days before the workshop (aside from the automated emails) helps make the rsvp count be more true. (does that make sense?)
If we need to raise the student count to more, we can.  With attendance counts on Bridgetroll, you can go up but can't go down.

K, hope y'all are having a good day.

**Comment by aneyzberg** [comment] 2015-07-30 23:12
thanks for doing that @iisa!

**Comment by ange3** [comment] 2015-08-05 05:44
Anyone have a picture of last night's event? Giving a quick shout out about the great event at Indiegogo's All Hands tomorrow!

**Comment by aneyzberg** [comment] 2015-08-05 06:21
Great Event! Closing this issue. Excited for the next one!

**Closed by aneyzberg** 2015-08-05 06:21 UTC
Labels: Needs Venue/Sponsor, SF

**Comment by aneyzberg** [comment] 2015-08-05 06:23
I think @ultrasaurus may have pictures from the event :)
